function au_s_d(p)
%
%  Deletes the global data that has been generated by 'au_s_i'.
%
%  Calling sequence:
%
%    au_s_d
%
%  Input:
%
%    p         vector containing the ADI shift parameters.
%
%
%  LYAPACK 1.6 (Jens Saak, October 2007)

global LP_LC LP_UC LP_aC LP_oC LP_SC

clear global LP_LC LP_UC LP_aC LP_oC LP_SC



