function msns_s_d(p)
%
%  Deletes the global data that has been generated by 'msns_s_i'.
%
%  Calling sequence:
%
%    msns_s_d(p)
%
%  Input:
%
%    p         vector containing the ADI shift parameters.
%
%
%  LYAPACK 1.6 (Jens Saak, October 2007)

l = length(p);

global LP_UC

clear global LP_UC;



