function munu_s_d(p)
%
%  Deletes the global data that has been generated by 'munu_s_i'.
%
%  Calling sequence:
%
%    munu_s_d(p)
%
%  Input:
%
%    p         vector containing the ADI shift parameters.
%
%
%  LYAPACK 1.6 (Jens Saak, October 2007)

l = length(p);

global LP_UC LP_LC

clear global LP_UC LP_LC


