function [files,logo,web,year] = dataForDoc()
% This function provides additional data that is necessary to generate the
% documentation


%% Files

proj_dir = fileparts(fileparts(mfilename('fullpath')));

files = {...
    [proj_dir filesep 'src' filesep 'MOR' ] ,...
	[proj_dir filesep 'src' filesep 'MOR' filesep 'ltiMor' filesep 'classic'] ,...
	[proj_dir filesep 'src' filesep 'MOR' filesep 'ltiMor' filesep 'stateOfTheArt'] ,...
	[proj_dir filesep 'src' filesep 'extras'] ,...
    [proj_dir filesep 'demos' filesep 'sssMOR_gettingStarted.m'] ,...
	};


%% Logo

logo = sprintf('%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s',...
    '%   <td style="background-color:#ffffff; border:0; width:25%; vertical-align:middle; text-align:center">',...
    '%             <img src="img/logo_sssMOR_long.png" alt="sssMOR_Logo" height="40px">',...
    '%      </td>', ...
    '%   <td style="background-color:#ffffff; border:0; width:25%; vertical-align:middle; text-align:center">',...
    '%      <img src="img/MORLAB_Logo.jpg" alt="MORLAB_Logo" height="40px"></td>', ...
    '%   <td style="background-color:#ffffff; border:0; width:25%; vertical-align:middle; text-align:center">',...
    '%      <img src="img/Logo_Textzusatz_rechts_engl_Chair.png" alt="RT_Logo" height="40px"></td>', ...
    '%   <td style="background-color:#ffffff; border:0; width:25%; vertical-align:middle; text-align:center">',...
    '%      <img src="img/TUM-logo.png" alt="TUM_Logo" height="40px"></td>');

%% Web

web = sprintf('%s',...
	'%        <a href="https://www.rt.mw.tum.de/?sssMOR">Website</a>');

%% Year of the first release

year = 2015;